title: Researcher
url: "https://a1inani.github.io/"
baseurl: "/index"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/a1inani"
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/researcher/"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
