title: Alinani Simukanga
url: "https://a1inani.github.io/"
baseurl: "/"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/a1inani"
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"  
 - name: "CV"
   link: "Alinani_CV.pdf"
 - name: "Contact"
   link: "contact"
